before_commands:
    - "composer install --dev --prefer-source"
tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit -c phpunit.xml.dist
        filter:
            paths: ["src/*"]
            excluded_paths:       ["*/Tests/*"]
    php_loc:
        enabled: true
        excluded_dirs:        ["*/Tests/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
            excluded_paths:       ["*/Tests/*"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["src/*"]
            excluded_paths:       ["*/Tests/*"]
